# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=15000)),
                ('youtube_video', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 18, 1, 30, 41, 824820, tzinfo=utc))),
            ],
        ),
    ]
