# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 18, 1, 30, 52, 287391, tzinfo=utc)),
        ),
    ]
