# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20170614_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 0, 57, 56, 657400)),
        ),
    ]
