# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20170618_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='youtube_video',
        ),
        migrations.AddField(
            model_name='post',
            name='soundcloud',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 18, 22, 16, 42, 709257, tzinfo=utc)),
        ),
    ]
