# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 00:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 2, 40, 28, 112400)),
        ),
    ]
