# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20170614_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 23, 46, 59, 308000)),
        ),
    ]
