# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 22:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20170619_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 18, 22, 40, 40, 569775, tzinfo=utc)),
        ),
    ]
