# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20170619_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 18, 22, 53, 43, 685908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='soundcloud',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
