# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 01:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20170615_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 3, 6, 41, 297000)),
        ),
    ]
