# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 01:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20170616_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 3, 8, 21, 89000)),
        ),
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 6, 16, 3, 8, 21, 89000)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2017, 6, 16)),
        ),
    ]
