# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20170620_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 13, 54, 24, 226925, tzinfo=utc)),
        ),
    ]
