# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 01:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20170616_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2017, 6, 16)),
        ),
        migrations.AlterField(
            model_name='post',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 3, 10, 52, 83000)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=datetime.time(3, 10, 52, 83000)),
        ),
    ]
