# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 01:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20170616_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dateAndTime',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pinned',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.AddField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 3, 28, 57, 334000)),
        ),
    ]
