# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20170616_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 14, 44, 42, 352182, tzinfo=utc)),
        ),
    ]
